
#Post 
POST http://127.0.0.1:8080/todos HTTP/1.1
content-type: application/json
{
    "nome": "Todo 1",
    "descricao": "Desc todo 1",
    "prioridade": 1
}

###

GET http://127.0.0.1:8080/todos HTTP/1.1
